config/routes.rb
Rails.application.routes.draw do

  resources :tags

  get '/questions'      => 'questions#index'
  get '/questions/ask'  => 'questions#ask'
  post 'questions/create' => 'questions#create'

  resources :ask_question_dashboards

  resources :unanswered_dashboards

  resources :user_dashboards

  resources :tag_dashboards

  root      to:     'question_dashboards#index'
  resources         :dashboards

  get  '/signup'            => 'users#new'

  get   '/signin'           => 'sessions#new'
  post  '/signin'           => 'sessions#create'
  get   '/signout'          => 'sessions#destroy'

  get   '/forgot_password'  => 'session#rescue'

  resources :users

end

app/models/user_dashboard.rb
class UserDashboard < ActiveRecord::Base
end

app/controllers/user_dashboards_controller.rb
class UserDashboardsController < ApplicationController
  before_action :set_user_dashboard, only: [:show, :edit, :update, :destroy]

  # GET /user_dashboards
  # GET /user_dashboards.json
  def index
    @user_dashboards = UserDashboard.all
  end

  # GET /user_dashboards/1
  # GET /user_dashboards/1.json
  def show
  end

  # GET /user_dashboards/new
  def new
    @user_dashboard = UserDashboard.new
  end

  # GET /user_dashboards/1/edit
  def edit
  end

  # POST /user_dashboards
  # POST /user_dashboards.json
  def create
    @user_dashboard = UserDashboard.new(user_dashboard_params)

    respond_to do |format|
      if @user_dashboard.save
        format.html { redirect_to @user_dashboard, notice: 'User dashboard was successfully created.' }
        format.json { render :show, status: :created, location: @user_dashboard }
      else
        format.html { render :new }
        format.json { render json: @user_dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_dashboards/1
  # PATCH/PUT /user_dashboards/1.json
  def update
    respond_to do |format|
      if @user_dashboard.update(user_dashboard_params)
        format.html { redirect_to @user_dashboard, notice: 'User dashboard was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_dashboard }
      else
        format.html { render :edit }
        format.json { render json: @user_dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_dashboards/1
  # DELETE /user_dashboards/1.json
  def destroy
    @user_dashboard.destroy
    respond_to do |format|
      format.html { redirect_to user_dashboards_url, notice: 'User dashboard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_dashboard
      @user_dashboard = UserDashboard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_dashboard_params
      params[:user_dashboard]
    end
end

app/helpers/user_dashboards_helper.rb
module UserDashboardsHelper
end

app/views/user_dashboards/_form.html.erb
<%= form_for(@user_dashboard) do |f| %>
  <% if @user_dashboard.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(@user_dashboard.errors.count, "error") %> prohibited this user_dashboard from being saved:</h2>

        <ul>
          <% @user_dashboard.errors.full_messages.each do |message| %>
              <li><%= message %></li>
          <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_dashboards/edit.html.erb
<h1>Editing user_dashboard</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_dashboard %> |
<%= link_to 'Back', user_dashboards_path %>

app/views/user_dashboards/index.html.erb
<h1>Listing user_dashboards</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_dashboards.each do |user_dashboard| %>
      <tr>
        <td><%= link_to 'Show', user_dashboard %></td>
        <td><%= link_to 'Edit', edit_user_dashboard_path(user_dashboard) %></td>
        <td><%= link_to 'Destroy', user_dashboard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User dashboard', new_user_dashboard_path %>

app/views/user_dashboards/new.html.erb
<h1>New user_dashboard</h1>

<%= render 'form' %>

<%= link_to 'Back', user_dashboards_path %>

app/views/user_dashboards/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_dashboard_path(@user_dashboard) %> |
<%= link_to 'Back', user_dashboards_path %>