config/routes.rb
Rails.application.routes.draw do

  resources :tags

  get '/questions'      => 'questions#index'
  get '/questions/ask'  => 'questions#ask'
  post 'questions/create' => 'questions#create'

  resources :ask_question_dashboards

  resources :unanswered_dashboards

  resources :user_dashboards

  resources :tag_dashboards

  root      to:     'question_dashboards#index'
  resources         :dashboards

  get  '/signup'            => 'users#new'

  get   '/signin'           => 'sessions#new'
  post  '/signin'           => 'sessions#create'
  get   '/signout'          => 'sessions#destroy'

  get   '/forgot_password'  => 'session#rescue'

  resources :users

end

app/models/question_dashboard.rb
class QuestionDashboard < ActiveRecord::Base
end

app/controllers/question_dashboards_controller.rb
class QuestionDashboardsController < ApplicationController
  before_action :set_question_dashboard, only: [:show, :edit, :update, :destroy]

  # GET /question_dashboards
  # GET /question_dashboards.json
  def index
    @question_dashboards = QuestionDashboard.all
  end

  # GET /question_dashboards/1
  # GET /question_dashboards/1.json
  def show
  end

  # GET /question_dashboards/new
  def new
    @question_dashboard = QuestionDashboard.new
  end

  # GET /question_dashboards/1/edit
  def edit
  end

  # POST /question_dashboards
  # POST /question_dashboards.json
  def create
    @question_dashboard = QuestionDashboard.new(question_dashboard_params)

    respond_to do |format|
      if @question_dashboard.save
        format.html { redirect_to @question_dashboard, notice: 'Question dashboard was successfully created.' }
        format.json { render :show, status: :created, location: @question_dashboard }
      else
        format.html { render :new }
        format.json { render json: @question_dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /question_dashboards/1
  # PATCH/PUT /question_dashboards/1.json
  def update
    respond_to do |format|
      if @question_dashboard.update(question_dashboard_params)
        format.html { redirect_to @question_dashboard, notice: 'Question dashboard was successfully updated.' }
        format.json { render :show, status: :ok, location: @question_dashboard }
      else
        format.html { render :edit }
        format.json { render json: @question_dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /question_dashboards/1
  # DELETE /question_dashboards/1.json
  def destroy
    @question_dashboard.destroy
    respond_to do |format|
      format.html { redirect_to question_dashboards_url, notice: 'Question dashboard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question_dashboard
      @question_dashboard = QuestionDashboard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_dashboard_params
      params[:question_dashboard]
    end
end

app/helpers/question_dashboards_helper.rb
module QuestionDashboardsHelper
end

app/views/question_dashboards/_form.html.erb
<%= form_for(@question_dashboard) do |f| %>
  <% if @question_dashboard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question_dashboard.errors.count, "error") %> prohibited this question_dashboard from being saved:</h2>

      <ul>
      <% @question_dashboard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/question_dashboards/edit.html.erb
<h1>Editing question_dashboard</h1>

<%= render 'form' %>

<%= link_to 'Show', @question_dashboard %> |
<%= link_to 'Back', question_dashboards_path %>

app/views/question_dashboards/index.html.erb
<!-- @questions.each do |question| -->
<% @question_dashboards.each do |question_dashboard| %>
<div class="container">
  <div id="sub-header">
    <h1>All questions</h1>
  </div>

  <div class="question-summary">
    <div class="stats-container">
      <div class="stats">
        <div class="votes">
            <strong>0</strong>
            votes
        </div>
        <div class="answers">
            <strong>0</strong>
            answers
        </div>
      </div>
      <div class="views">2 views</div>
    </div>
    <div class="summary">
      <h3>
        <a>VB.Net Set SplitContainer Height with Vertical Orientation</a>
      </h3>

      <div>I'm using a SplitContainer with vertical Orientation, and I need to set the height of it depending on a
        DataGrid inside Panel1... How can I set the Height of the entire SplitContainer in Runtime? The ...
      </div>

      <div class="tags">
        <a class="post-tag" href="/questions/tagged/jquery">jquery</a>
        <a class="post-tag" href="/questions/tagged/html5">html5</a>
        <a class="post-tag" href="/questions/tagged/sortable">sortable</a>
      </div>
      <div class="more-info">
        <a class="post-time" href="">asked 21s ago</a>
        <a href="" class="user">Nick Miller</a>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/question_dashboards/new.html.erb
<h1>New question_dashboard</h1>

<%= render 'form' %>

<%= link_to 'Back', question_dashboards_path %>

app/views/question_dashboards/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_question_dashboard_path(@question_dashboard) %> |
<%= link_to 'Back', question_dashboards_path %>