config/routes.rb
Rails.application.routes.draw do

  resources :tags

  get '/questions'      => 'questions#index'
  get '/questions/ask'  => 'questions#ask'
  post 'questions/create' => 'questions#create'

  resources :ask_question_dashboards

  resources :unanswered_dashboards

  resources :user_dashboards

  resources :tag_dashboards

  root      to:     'question_dashboards#index'
  resources         :dashboards

  get  '/signup'            => 'users#new'

  get   '/signin'           => 'sessions#new'
  post  '/signin'           => 'sessions#create'
  get   '/signout'          => 'sessions#destroy'

  get   '/forgot_password'  => 'session#rescue'

  resources :users

end

app/models/unanswered_dashboard.rb
class UnansweredDashboard < ActiveRecord::Base
end

app/controllers/unanswered_dashboards_controller.rb
class UnansweredDashboardsController < ApplicationController
  before_action :set_unanswered_dashboard, only: [:show, :edit, :update, :destroy]

  # GET /unanswered_dashboards
  # GET /unanswered_dashboards.json
  def index
    @unanswered_dashboards = UnansweredDashboard.all
  end

  # GET /unanswered_dashboards/1
  # GET /unanswered_dashboards/1.json
  def show
  end

  # GET /unanswered_dashboards/new
  def new
    @unanswered_dashboard = UnansweredDashboard.new
  end

  # GET /unanswered_dashboards/1/edit
  def edit
  end

  # POST /unanswered_dashboards
  # POST /unanswered_dashboards.json
  def create
    @unanswered_dashboard = UnansweredDashboard.new(unanswered_dashboard_params)

    respond_to do |format|
      if @unanswered_dashboard.save
        format.html { redirect_to @unanswered_dashboard, notice: 'Unanswered dashboard was successfully created.' }
        format.json { render :show, status: :created, location: @unanswered_dashboard }
      else
        format.html { render :new }
        format.json { render json: @unanswered_dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /unanswered_dashboards/1
  # PATCH/PUT /unanswered_dashboards/1.json
  def update
    respond_to do |format|
      if @unanswered_dashboard.update(unanswered_dashboard_params)
        format.html { redirect_to @unanswered_dashboard, notice: 'Unanswered dashboard was successfully updated.' }
        format.json { render :show, status: :ok, location: @unanswered_dashboard }
      else
        format.html { render :edit }
        format.json { render json: @unanswered_dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unanswered_dashboards/1
  # DELETE /unanswered_dashboards/1.json
  def destroy
    @unanswered_dashboard.destroy
    respond_to do |format|
      format.html { redirect_to unanswered_dashboards_url, notice: 'Unanswered dashboard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unanswered_dashboard
      @unanswered_dashboard = UnansweredDashboard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unanswered_dashboard_params
      params[:unanswered_dashboard]
    end
end

app/helpers/unanswered_dashboards_helper.rb
module UnansweredDashboardsHelper
end

app/views/unanswered_dashboards/_form.html.erb
<%= form_for(@unanswered_dashboard) do |f| %>
  <% if @unanswered_dashboard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@unanswered_dashboard.errors.count, "error") %> prohibited this unanswered_dashboard from being saved:</h2>

      <ul>
      <% @unanswered_dashboard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/unanswered_dashboards/edit.html.erb
<h1>Editing unanswered_dashboard</h1>

<%= render 'form' %>

<%= link_to 'Show', @unanswered_dashboard %> |
<%= link_to 'Back', unanswered_dashboards_path %>

app/views/unanswered_dashboards/index.html.erb
<h1>Listing unanswered_dashboards</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @unanswered_dashboards.each do |unanswered_dashboard| %>
      <tr>
        <td><%= link_to 'Show', unanswered_dashboard %></td>
        <td><%= link_to 'Edit', edit_unanswered_dashboard_path(unanswered_dashboard) %></td>
        <td><%= link_to 'Destroy', unanswered_dashboard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Unanswered dashboard', new_unanswered_dashboard_path %>

app/views/unanswered_dashboards/new.html.erb
<h1>New unanswered_dashboard</h1>

<%= render 'form' %>

<%= link_to 'Back', unanswered_dashboards_path %>

app/views/unanswered_dashboards/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_unanswered_dashboard_path(@unanswered_dashboard) %> |
<%= link_to 'Back', unanswered_dashboards_path %>